POST http://localhost:3000/workouts
Content-Type: application/json

{
    "name": "legs",
    "date": "06/25/23"
}

###

GET http://localhost:3000/workouts

###

DELETE http://localhost:3000/workouts/64b9c6ed264a894e1075b4ed